import 'package:get/get.dart';

class Languages extends Translations {
  static getLocalizedKey(String key) {
    String currentLanguageCode = Get.locale!.languageCode;
    print('Localized key is: ${key}_$currentLanguageCode');
    return '${key}_$currentLanguageCode';
  }

  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'no_faqs_found': 'No Faqs found',
          'about_inna_home': 'About Inna Home',
          'Faqs': 'Faqs',
          'please_login': 'Please Login',
          'are_you_sure_to_login': 'Are you sure to login?',
          'to_logout': 'Are you sure to logout?',
          'profile_updated_successfully': 'Profile updated successfully',
          'Mobile': 'Mobile',
          'notifications_not_found': 'Notifications are not found',
          'all_products': 'All Products',
          'top_rated': 'Top Rated',
          'top_rated_products': 'Top Rated Products',
          // 'new_in': 'New In',
          'new_arrivals': 'New Arrivals',
          'categories': 'Categories',
          'sub_category_not_found': 'Subcategory not found',
          'removed_from_whislist': 'Product successfully removed from wishlist',
          'whishlist_removed': 'Wishlist removed',
          'added_to_whishlist': 'Product successfully added to wishlist',
          'whishlist_added': 'Wishlist added',
          'submit': 'Submit',
          'contact_us': 'Contact Us',
          'something_went_wrong': 'Something went wrong please try again',
          'error': 'Error!!',
          'request_added_successfully': 'Request added successflully',
          'success': 'Success!!',
          'do_you_really_want_to_delete_all_the_products_from_the_cart':
              'Do you really want to delete all products from cart?',
          'are_you_sure': 'Are you sure?',
          'do_you_want_to_remove_this':
              'Do you want to remove this product from cart',
          'remove_from_cart': 'Remove from cart',
          'add_address_for_check_out': 'Please add address for checkout',
          'add_address': 'Add address',
          'your_order_is_placed': 'Your order is successfully placed',
          'order_success': 'Order Success',
          'total_price': 'Total price',
          'verify_before_checkout': 'Verify before checkout',
          'checkout': 'Checkout',
          'country_name': 'Country name',
          'phone_number_with_country_code': 'Phone number with country code',
          'already_have_an_account': 'Already have an Account? ',
          'register': 'Register',
          "dont_have_an_account": "Don't Have an Account?",
          "hello": "Hello world!",
          "sportsTalent": "Horitoki",
          "services": "Categories",
          "sports": "Sports",
          "fitness_centers": "Fitness\nCenters",
          "personal_trainers": "Personal\nTrainers",
          "federations": "Federations",
          "clubs": "Clubs",
          'talents': "Talents",
          "new_in": "New In",
          "view_all": "View All",
          "recently_joined": "Recently Joined",
          "profile": "Profile",
          "blog": "Blog",
          "shop": "Shop",
          "wishlist": "Wishlist",
          "notifications": "Notifications",
          "my_orders": "My Orders",
          "faqs": "FAQs",
          "feedback": "Feedback",
          "privacy": "Privacy Policy",
          "settings": "Settings",
          "logout": "Logout",
          "edit_profile": "Edit Profile",
          "account_info": "Account Info",
          "my_addresses": "My Addresses",
          "change_password": "Change Password",
          "change_my_password": "Change My Password",
          "login": "Login",
          "remember_me": "Remember Me",
          "forget_password": "Forget Password",
          "register": "Register",
          "sign_up": "Sign Up",
          "username": "Username",
          "email": "Email",
          "mobile": "Mobile",
          "password": "Password",
          "confirm_password": "Confirm Password",
          "age": "Age",
          "location": "Location",
          "gender": "Gender",
          "male": "Male",
          "female": "Female",
          "reset_password":
              "Enter your registered email below to\nreceive password reset instructions",
          "send": "Send",
          "new_address": "Add New Address",
          "old_password": "Old Password",
          "new_password": "New Password",
          "change": "Change",
          "comments": "Comments",
          "add_comment": "Add a comments",
          "more_products": "Scroll down to view more products",
          "related_products": "Related Products",
          "reviews": "Reviews",
          "add_to_cart": "Add to Cart",
          "based_on": "Based on",
          "just_now": "Today",
          "days_ago": "days ago",
          "write_review": "Write a Review",
          "rate": "Rate",
          "your_review": "Write your review",
          "write_a_review": "Write a review",
          "review_text": "Would you like to write anything about this product?",
          "remaining_characters": "characters remaining",
          "submit_review": "Submit Review",
          "required_field": "Required Field",
          "keyword_search": "Search using keywords",
          "about_sport_talent": "About Sport Talent",
          "support": "Support",
          "rate_experience": "Please rate your experience",
          "additional_comment": "Additional comments",
          "policy_policy": "Privacy Policy",
          "language": "Language",
          "about_us": "About us",
          "rate_us": "Rate us",
          "my_cart": "My Cart",
          "order": "Order",
          "address1": "Address",
          "address": "Address",
          "address2": "Address 2",
          "review_&_pay": "Review & Pay",
          "place_order": "Place Order",
          "subtotal": "Subtotal",
          "shipping": "Shipping",
          "discount": "Discount",
          "total": "TOTAL",
          "deliver_note": "Please note that the delivery will take 3-7 days",
          "confirm_order": "Confirm Order",
          "continue": "Continue",
          "credit_card": "Credit Card",
          "card_no": "Card Number",
          "expiry_date": "Expiry Date (mm/yy)",
          "cvv": "CVV",
          "benifits": "Benifits",
          "add_coupan": "Add Coupon Code",
          "buy_now": "Buy Now",
          "my_bookings": "My Bookings",
          "bookigs_not_found": "Bookings not found on selected date",
          "offers": "Offers",
          "starting_with": 'Starting with',
          "working_hours": "Working Hours",
          "book_now": "Book Now",
          "book_a_pitch": "Book a pitch",
          "pick_duration": "Pick duration of booking",
          "booking_type": "Booking type",
          "pick_date": "Pick Date and Time",
          "monday": "Monday",
          "tuesday": "Tuesday",
          "wednesday": "Wednesday",
          "thursday": "Thursday",
          "friday": "Friday",
          "saturday": "Saturday",
          "sunday": "Sunday",
          "total_price": "Total Price",
          "proceed": "Proceed",
          "confirm_booking": "Confirm Booking",
          "booking": "Booking Details",
          "facilites": "Facilities",
          "book_field": "Book Field",
          "whats_new": "Scroll down to see what's new",
          "search": "Search",
          "search_text": "What are you looking for?",
          "filter": "Filter",
          "categories": "Category",
          "brands": "Brands",
          "sort": "Sort",
          "new_arrival": "New Arriavals",
          "low_to_high": "Low to High",
          "high_to_low": "High to Low",
          "top_rated": "Top Rated",
          "apply": "Apply",
          "add_your_talent": "Add Your Talent",
          "search_talent": "Search Talent ...",
          "view": "View",
          "talent": "Talent",
          "likes": "Likes",
          "watch_video": "Click to watch the video section",
          "contact_talent": "Contact this talent",
          "form_fill": "Kindly fill the form below",
          "company_name": "Company/Person Name",
          "contact_no": "Contact Number",
          "reason_for_contact": "Reason for contacting this talent",
          "live_chat": "Live Chat",
          "type_something": "Type something",
          "enter_coupan": "Enter coupon code",
          "coupan_invalid": "Coupon Code Invalid!",
          "retry": "Retry",
          "discount_granted": "Discount Granted!",
          "code_expired": "Coupon Code Expired!",
          "order_successful": "Order Successful",
          "was_received": "was received",
          "check_email":
              "Please check your order confirmation email for delivery timelines",
          "continue_shopping": "Continue Shopping",
          "pending": "PENDING",
          "canceled": "CANCELED",
          "delivered": "DELIVERED",
          "shipped": "SHIPPED",
          "service_charge": "Service Charge",
          "birthday": "Birthday",
          "country_code": "Country Code",
          "phone": "Phone",
          "country": "Country",
          "city": "City",
          "postal_code": "Postal code",
          "save": "Save",
          "fill_form": "Please fill the form below",
          "full_name": "Full name",
          "parent_contact": "Parent contact number",
          "describe": "Describe this talent",
          "scroll_down": "Scroll down to view",
          "are_you_sure": "Are you sure!",
          "want_to_exit": "Do you want to exit this app?",
          "change_lang_msg": "Dou want to change language?",
          "yes": "Yes",
          "no": "No",
          "alert": "Alert!",
          "ok": "Ok",
          "network_error": "Network error",
          "connect_network": 'Please connect to a network',
          "requestFailed": "Resuest failed",
          "email_required": "Email is required",
          "password_required": "Password is required",
          "password_too_short": "The password is too short",
          "username_required": "Username is required",
          "phone_required": "Phone no is required",
          "password_should_match": "Please make sure your passwords match",
          "age_required": "Age is required",
          "location_required": "Location is required",
          "invalid_email": "Invalid Email",
          "password_invalid": "Invalid Password",
          "not_given": "Not Given",
          "name": "Name",
          "sure_to_delete": "Are you sure to delete this address?",
          "check_order_confirmation": "Please check your order confirmation ",
          "email_for_delivery": "Email for delivery timeline",
          "sure_to_delete_product": "Are you sure to delete this product",
          "add_review": "Please add your reveiw",
          "rate_talent": "Rate Talent",
          "sure_to_cancel_booking": "Are you sure to cancel this booking?",
          'products': "Products",
          "cart_empty": "Please ensure you have added product and address",
          "home": 'Home',
          "payment_success": "Payment Successful",
          "your_feedback": "Your feedback goes here",
          "sure": 'Are you sure?',
          "sure_add_feedback": "Do you want add this feedback?",
          "400": "400",
          "remaining_chars": " characters remaining",
          "maximum_chars_reached": "Maximum characters reached",
          "review": "reviews",
          "day_ago": "day ago",
          "off": "OFF",
          "years": "years",
          "fill_below_form": "Please fill the form below",
          "full_name_required": "Full name is required",
          "parent_contact_required": "Parent contact is required",
          "describe_talent": "Describe this talent",
          "preferred_photo": "(1080 x 1080 px preferred)",
          "preferred_video": "(1280 x 1720 px preferred)",
          "found": "found",
          "services_not_found": "No Service found",
          "total_capital": "TOTAL",
          'view_talent': "View Talents",
          "add_new_address": "Add New Address",
          // "submit": "Submit",
          "reschedule": "Reschedule",
          "cancel": "Cancel",
          "reschedule_booking": "Reschedule Booking",
          "change_booking_date_time": "Change booking date and time",
          "rescheduled": "Rescheduled",
          "successfully_rescheduled": "Booking successfully rescheduled",
          "error_while_rescheduling":
              "An error occured while rescheduling booking",
          "error_while_canceling": "An error occured while canceling booking",
          "edit_address": "Edit Address",
          "success": "Success",
          "address_deleted_successfully": "Address deleted successfully!",
          "quit_payment": "Do you want to quit payments",
          "no_order_created": "No order created yet",
          "empty_wishlist": "Wishlist is empty",
          "no_support_faqs": "No FAQ's found for about support",
          "no_talent_faqs": "No FAQ's found for about talent",
          "thanks": "Thanks",
          "feedback_recorded": "Your feedback is recorded",
          "rating_recorded": "You rating is recorded",
          "no_blogs": "Blogs are not uploaded yet",
          "address_empty":
              "Please make sure you have added and selected address",
          "blogs_not_found": "Blogs not found",
          "service_not_found": "Service not found",
          "offers_not_found": "Offers not found",
          "out_of_stock": "Out of Stock",
          "added_success": "Successfully Added",
          "thanks_for_adding_talent":
              "Thanks for adding your talent. Please be patient till admin approval",
          "make_sure": "Please make sure you have added images and video",
          "new_products": "Scroll down to see what's new",
          "empty_cart": "Empty Cart",
          "add_rating": "Please select your rating and add comment",
          "validate_email": "Enter a valid email address",
          "okk": "Ok",
          "cancell": "Cancel",
          "already_booked": "This field is already booked at the selected time",
          "scroll_to_view": "Scroll down to view",
          "bookings_not_created": "Bookings not created yet",
          "searched_prod_not_found": "Products not found",
          "sure_to_delete_review": "Are you sure to delete this review",
          "update_review": "Update Review",
          "press_book_now": "Press Book Now button to book this service",
          "press_buy_now": "Press Buy Now button to buy this product",
          "service_booking_success": "Service Booked Successfully",
          "added_data": "Please select talent type, gender and age",
          "recently_not_found": "Recently joinies not found",
          "please_signup": "Please Login",
          "signup": "Sign up",
          "oops": "Oops!",
          "signup_required":
              "It look like you are not Logged In, You need to login first...",
          'en': "English",
          'ar': "Arabic",
          "terms_and_conditions": "I have read and accept terms and conditions",
          "accept_terms": "Please accept the terms and conditions",
          "code": "Code",
          "country_code_required": "country code required",
          "offer_percentage": "Offer Percentage: ",
        },

        ///
        ///french
        ///
        ///

        'fr': {
          'no_faqs_found': 'Aucune FAQ trouvée',
          'about_inna_home': 'À propos d\'Inna Home',
          'Faqs': 'FAQs',
          'please_login': 'Veuillez vous connecter',
          'are_you_sure_to_login': 'Êtes-vous sûr de vouloir vous connecter?',
          'to_logout': 'Êtes-vous sûr de vouloir vous déconnecter?',
          'profile_updated_successfully': 'Profil mis à jour avec succès',
          'Mobile': 'Mobile',
          'notifications_not_found': 'Aucune notification trouvée',
          'all_products': 'Tous les produits',
          'top_rated': 'Les mieux notés',
          'top_rated_products': 'Produits les mieux notés',
          'new_in': 'Nouveautés',
          'new_arrivals': 'Nouveautés',
          'categories': 'Catégories',
          'sub_category_not_found': 'Sous-catégorie non trouvée',
          'removed_from_whislist':
              'Produit retiré avec succès de la liste de souhaits',
          'whishlist_removed': 'Liste de souhaits supprimée',
          'added_to_whishlist':
              'Produit ajouté avec succès à la liste de souhaits',
          'whishlist_added': 'Liste de souhaits ajoutée',
          'submit': 'Soumettre',
          'contact_us': 'Contactez-nous',
          'something_went_wrong':
              'Quelque chose s\'est mal passé, veuillez réessayer',
          'error': 'Erreur!!',
          'request_added_successfully': 'Demande ajoutée avec succès',
          'success': 'Succès!!',
          'do_you_really_want_to_delete_all_the_products_from_the_cart':
              'Voulez-vous vraiment supprimer tous les produits du panier?',
          'are_you_sure': 'Êtes-vous sûr?',
          'do_you_want_to_remove_this':
              'Voulez-vous supprimer ce produit du panier',
          'remove_from_cart': 'Retirer du panier',
          'add_address_for_check_out':
              'Veuillez ajouter une adresse pour passer à la caisse',
          'add_address': 'Ajouter une adresse',
          'your_order_is_placed': 'Votre commande a été passée avec succès',
          'order_success': 'Commande réussie',
          'total_price': 'Prix total',
          'verify_before_checkout': 'Vérifiez avant de passer à la caisse',
          'checkout': 'Caisse',
          'country_name': 'Nom du pays',
          'phone_number_with_country_code':
              'Numéro de téléphone avec code pays',
          'already_have_an_account': 'Vous avez déjà un compte? ',
          'register': 'S\'inscrire',
          "dont_have_an_account": "Vous n'avez pas de compte?",
          "hello": "Bonjour le monde!",
          "sportsTalent": "Horitoki",
          "services": "Catégories",
          "sports": "Sports",
          "fitness_centers": "Centres de\nfitness",
          "personal_trainers": "Entraîneurs\npersonnels",
          "federations": "Fédérations",
          "clubs": "Clubs",
          'talents': "Talents",
          // "new_in": "Nouveauté",
          "view_all": "Voir tout",
          "recently_joined": "Récemment rejoint",
          "profile": "Profil",
          "blog": "Blog",
          "shop": "Boutique",
          "wishlist": "Liste de souhaits",
          "notifications": "Notifications",
          "my_orders": "Mes commandes",
          "faqs": "FAQs",
          "feedback": "Retour d'information",
          "privacy": "Politique de confidentialité",
          "settings": "Paramètres",
          "logout": "Déconnexion",
          "edit_profile": "Modifier le profil",
          "account_info": "Informations sur le compte",
          "my_addresses": "Mes adresses",
          "change_password": "Changer le mot de passe",
          "change_my_password": "Changer mon mot de passe",
          "login": "Se connecter",
          "remember_me": "Se souvenir de moi",
          "forget_password": "Mot de passe oublié",
          "register": "S'inscrire",
          "sign_up": "S'inscrire",
          "username": "Nom d'utilisateur",
          "email": "Email",
          "mobile": "Mobile",
          "password": "Mot de passe",
          "confirm_password": "Confirmer le mot de passe",
          "age": "Âge",
          "location": "Emplacement",
          "gender": "Genre",
          "male": "Homme",
          "female": "Femme",
          "reset_password":
              "Entrez votre email enregistré ci-dessous pour\nrecevoir les instructions de réinitialisation du mot de passe",
          "send": "Envoyer",
          "new_address": "Ajouter une nouvelle adresse",
          "old_password": "Ancien mot de passe",
          "new_password": "Nouveau mot de passe",
          "change": "Changer",
          "comments": "Commentaires",
          "add_comment": "Ajouter un commentaire",
          "more_products": "Faites défiler pour voir plus de produits",
          "related_products": "Produits associés",
          "reviews": "Avis",
          "add_to_cart": "Ajouter au panier",
          "based_on": "Basé sur",
          "just_now": "Aujourd'hui",
          "days_ago": "il y a jours",
          "write_review": "Écrire un avis",
          "rate": "Taux",
          "your_review": "Rédigez votre avis",
          "write_a_review": "Écrire un avis",
          "review_text": "Voulez-vous écrire quelque chose sur ce produit?",
          "remaining_characters": "caractères restants",
          "submit_review": "Envoyer l'avis",
          "required_field": "Champ requis",
          "keyword_search": "Recherche par mots-clés",
          "about_sport_talent": "À propos du talent sportif",
          "support": "Soutien",
          "rate_experience": "Veuillez évaluer votre expérience",
          "additional_comment": "Commentaires supplémentaires",
          "policy_policy": "Politique de confidentialité",
          "language": "Langue",
          "about_us": "À propos de nous",
          "rate_us": "Évaluez-nous",
          "my_cart": "Mon panier",
          "order": "Commande",
          "address1": "Adresse",
          "address": "Adresse",
          "address2": "Adresse 2",
          "review_&_pay": "Examiner et payer",
          "place_order": "Passer la commande",
          "subtotal": "Sous-total",
          "shipping": "Livraison",
          "discount": "Remise",
          "total": "TOTAL",
          "deliver_note": "Veuillez noter que la livraison prendra 3 à 7 jours",
          "confirm_order": "Confirmer la commande",
          "continue": "Continuer",
          "credit_card": "Carte de crédit",
          "card_no": "Numéro de carte",
          "expiry_date": "Date d'expiration (mm/aa)",
          "cvv": "CVV",
          "benifits": "Avantages",
          "add_coupan": "Ajouter un code coupon",
          "buy_now": "Acheter maintenant",
          "my_bookings": "Mes réservations",
          "bookigs_not_found":
              "Aucune réservation trouvée à la date sélectionnée",
          "offers": "Offres",
          "starting_with": 'Commence par',
          "working_hours": "Heures de travail",
          "book_now": "Réserver maintenant",
          "book_a_pitch": "Réserver un terrain",
          "pick_duration": "Choisir la durée de la réservation",
          "booking_type": "Type de réservation",
          "pick_date": "Choisir la date et l'heure",
          "monday": "Lundi",
          "tuesday": "Mardi",
          "wednesday": "Mercredi",
          "thursday": "Jeudi",
          "friday": "Vendredi",
          "saturday": "Samedi",
          "sunday": "Dimanche",
          "total_price": "Prix total",
          "proceed": "Procéder",
          "confirm_booking": "Confirmer la réservation",
          "booking": "Détails de la réservation",
          "facilites": "Installations",
          "book_field": "Réserver un terrain",
          "whats_new": "Faites défiler pour voir les nouveautés",
          "search": "Recherche",
          "search_text": "Que recherchez-vous?",
          "filter": "Filtre",
          "categories": "Catégorie",
          "brands": "Marques",
          "sort": "Trier",
          "new_arrival": "Nouveautés",
          "low_to_high": "De bas en haut",
          "high_to_low": "De haut en bas",
          "top_rated": "Les mieux notés",
          "apply": "Appliquer",
          "add_your_talent": "Ajouter votre talent",
          "search_talent": "Rechercher le talent ...",
          "view": "Voir",
          "talent": "Talent",
          "likes": "J'aime",
          "watch_video": "Cliquez pour regarder la section vidéo",
          "contact_talent": "Contacter ce talent",
          "form_fill": "Veuillez remplir le formulaire ci-dessous",
          "company_name": "Nom de la société/personne",
          "contact_no": "Numéro de contact",
          "reason_for_contact": "Raison de contacter ce talent",
          "live_chat": "Chat en direct",
          "type_something": "Tapez quelque chose",
          "enter_coupan": "Entrez le code coupon",
          "coupan_invalid": "Code coupon invalide!",
          "retry": "Réessayer",
          "discount_granted": "Remise accordée!",
          "code_expired": "Code coupon expiré!",
          "order_successful": "Commande réussie",
          "was_received": "a été reçu",
          "check_email":
              "Veuillez consulter votre email de confirmation de commande pour les délais de livraison",
          "continue_shopping": "Continuer vos achats",
          "pending": "EN ATTENTE",
          "canceled": "ANNULÉE",
          "delivered": "LIVRÉE",
          "shipped": "EXPÉDIÉE",
          "service_charge": "Frais de service",
          "birthday": "Anniversaire",
          "country_code": "Code pays",
          "phone": "Téléphone",
          "country": "Pays",
          "city": "Ville",
          "postal_code": "Code postal",
          "save": "Enregistrer",
          "fill_form": "Veuillez remplir le formulaire ci-dessous",
          "full_name": "Nom complet",
          "parent_contact": "Numéro de contact du parent",
          "describe": "Décrire ce talent",
          "scroll_down": "Faites défiler pour voir",
          "are_you_sure": "Êtes-vous sûr!",
          "want_to_exit": "Voulez-vous quitter cette application?",
          "change_lang_msg": "Voulez-vous changer de langue?",
          "yes": "Oui",
          "no": "Non",
          "alert": "Alerte !",
          "ok": "Ok",
          "network_error": "Erreur réseau",
          "connect_network": "Veuillez vous connecter à un réseau",
          "requestFailed": "Échec de la requête",
          "email_required": "L'e-mail est requis",
          "password_required": "Le mot de passe est requis",
          "password_too_short": "Le mot de passe est trop court",
          "username_required": "Le nom d'utilisateur est requis",
          "phone_required": "Le numéro de téléphone est requis",
          "password_should_match":
              "Veuillez vous assurer que vos mots de passe correspondent",
          "age_required": "L'âge est requis",
          "location_required": "La localisation est requise",
          "invalid_email": "E-mail invalide",
          "password_invalid": "Mot de passe invalide",
          "not_given": "Non spécifié",
          "name": "Nom",
          "sure_to_delete":
              "Êtes-vous sûr de vouloir supprimer cette adresse ?",
          "check_order_confirmation":
              "Veuillez vérifier votre confirmation de commande ",
          "email_for_delivery": "E-mail pour les délais de livraison",
          "sure_to_delete_product":
              "Êtes-vous sûr de vouloir supprimer ce produit",
          "add_review": "Veuillez ajouter votre avis",
          "rate_talent": "Évaluer le talent",
          "sure_to_cancel_booking":
              "Êtes-vous sûr de vouloir annuler cette réservation ?",
          "products": "Produits",
          "cart_empty":
              "Veuillez vous assurer d'avoir ajouté des produits et une adresse",
          "home": "Accueil",
          "payment_success": "Paiement réussi",
          "your_feedback": "Votre avis ici",
          "sure": "Êtes-vous sûr ?",
          "sure_add_feedback": "Voulez-vous ajouter cet avis ?",
          "400": "400",
          "remaining_chars": " caractères restants",
          "maximum_chars_reached": "Nombre maximal de caractères atteint",
          "review": "avis",
          "day_ago": "il y a un jour",
          "off": "OFF",
          "years": "années",
          "fill_below_form": "Veuillez remplir le formulaire ci-dessous",
          "full_name_required": "Le nom complet est requis",
          "parent_contact_required": "Le contact parental est requis",
          "describe_talent": "Décrivez ce talent",
          "preferred_photo": "(préféré 1080 x 1080 px)",
          "preferred_video": "(préféré 1280 x 1720 px)",
          "found": "trouvé",
          "services_not_found": "Aucun service trouvé",
          "total_capital": "TOTAL",
          "view_talent": "Voir les talents",
          "add_new_address": "Ajouter une nouvelle adresse",
          // "submit": "Soumettre",
          "reschedule": "Replanifier",
          "cancel": "Annuler",
          "reschedule_booking": "Replanifier la réservation",
          "change_booking_date_time":
              "Changer la date et l'heure de la réservation",
          "rescheduled": "Replanifié",
          "successfully_rescheduled": "Réservation replanifiée avec succès",
          "error_while_rescheduling":
              "Une erreur s'est produite lors de la replanification de la réservation",
          "error_while_canceling":
              "Une erreur s'est produite lors de l'annulation de la réservation",
          "edit_address": "Modifier l'adresse",
          "success": "Succès",
          "address_deleted_successfully": "Adresse supprimée avec succès !",
          "quit_payment": "Voulez-vous abandonner les paiements",
          "no_order_created": "Aucune commande créée pour le moment",
          "empty_wishlist": "La liste de souhaits est vide",
          "no_support_faqs": "Aucune FAQ trouvée concernant le support",
          "no_talent_faqs": "Aucune FAQ trouvée concernant le talent",
          "thanks": "Merci",
          "feedback_recorded": "Votre avis est enregistré",
          "rating_recorded": "Votre note est enregistrée",
          "no_blogs": "Aucun blog n'a été téléchargé pour le moment",
          "address_empty":
              "Veuillez vous assurer d'avoir ajouté et sélectionné une adresse",
          "blogs_not_found": "Aucun blog trouvé",
          "service_not_found": "Service non trouvé",
          "offers_not_found": "Aucune offre trouvée",
          "out_of_stock": "En rupture de stock",
          "added_success": "Ajouté avec succès",
          "thanks_for_adding_talent":
              "Merci d'avoir ajouté votre talent. Veuillez patienter jusqu'à l'approbation de l'administrateur",
          "make_sure":
              "Veuillez vous assurer d'avoir ajouté des images et une vidéo",
          "new_products": "Faites défiler vers le bas pour voir les nouveautés",
          "empty_cart": "Panier vide",
          "add_rating":
              "Veuillez sélectionner votre note et ajouter un commentaire",
          "validate_email": "Entrez une adresse e-mail valide",
          "okk": "Ok",
          "cancell": "Annuler",
          "already_booked": "Ce champ est déjà réservé à l'heure sélectionnée",
          "scroll_to_view": "Faites défiler vers le bas pour voir",
          "bookings_not_created": "Aucune réservation créée pour le moment",
          "searched_prod_not_found": "Produits non trouvés",
          "sure_to_delete_review":
              "Êtes-vous sûr de vouloir supprimer cet avis",
          "update_review": "Mettre à jour l'avis",
          "press_book_now":
              "Appuyez sur le bouton Réserver maintenant pour réserver ce service",
          "press_buy_now":
              "Appuyez sur le bouton Acheter maintenant pour acheter ce produit",
          "service_booking_success": "Service réservé avec succès",
          "added_data":
              "Veuillez sélectionner le type de talent, le genre et l'âge",
          "recently_not_found": "Aucune nouvelle inscription récente trouvée",
          "please_signup": "Veuillez vous connecter",
          "signup": "S'inscrire",
          "oops": "Oups !",
          "signup_required":
              "Il semble que vous ne soyez pas connecté. Vous devez d'abord vous connecter...",
          "en": "Anglais",
          "ar": "Arabe",
          "terms_and_conditions":
              "J'ai lu et j'accepte les termes et conditions",
          "accept_terms": "Veuillez accepter les termes et conditions",
          "code": "Code",
          "country_code_required": "Code de pays requis",
          "offer_percentage": "Pourcentage de réduction : "
        },

        ////
        ///Neitherlands
        ///
        'nl_NL': {
          "no_faqs_found": "Geen FAQs gevonden",
          "about_inna_home": "Over Inna Home",
          "Faqs": "FAQs",
          "please_login": "Gelieve in te loggen",
          "are_you_sure_to_login": "Weet u zeker dat u wilt inloggen?",
          "to_logout": "Weet u zeker dat u wilt uitloggen?",
          "profile_updated_successfully": "Profiel succesvol bijgewerkt",
          "Mobile": "Mobiel",
          "notifications_not_found": "Meldingen niet gevonden",
          "all_products": "Alle Producten",
          "top_rated": "Top Beoordeeld",
          "top_rated_products": "Top Beoordeelde Producten",
          "new_in": "Nieuw Binnen",
          "new_arrivals": "Nieuwe Aankomsten",
          "categories": "Categorieën",
          "sub_category_not_found": "Subcategorie niet gevonden",
          "removed_from_whislist":
              "Product succesvol verwijderd uit verlanglijst",
          "whishlist_removed": "Verlanglijst verwijderd",
          "added_to_whishlist": "Product succesvol toegevoegd aan verlanglijst",
          "whishlist_added": "Verlanglijst toegevoegd",
          "submit": "Indienen",
          "contact_us": "Neem contact met ons op",
          "something_went_wrong": "Er is iets misgegaan, probeer het opnieuw",
          "error": "Fout!!",
          "request_added_successfully": "Verzoek succesvol toegevoegd",
          "success": "Succes!!",
          "do_you_really_want_to_delete_all_the_products_from_the_cart":
              "Wil je echt alle producten uit de winkelwagen verwijderen?",
          "are_you_sure": "Weet je het zeker?",
          "do_you_want_to_remove_this":
              "Wil je dit product uit de winkelwagen verwijderen",
          "remove_from_cart": "Verwijderen uit winkelwagen",
          "add_address_for_check_out": "Voeg een adres toe om af te rekenen",
          "add_address": "Adres toevoegen",
          "your_order_is_placed": "Uw bestelling is succesvol geplaatst",
          "order_success": "Bestelling succesvol",
          "total_price": "Totale prijs",
          "verify_before_checkout": "Controleer voor het afrekenen",
          "checkout": "Afrekenen",
          "country_name": "Landnaam",
          "phone_number_with_country_code": "Telefoonnummer met landcode",
          "already_have_an_account": "Heeft u al een account? ",
          "register": "Registreren",
          "dont_have_an_account": "Heeft u geen account?",
          "hello": "Hallo wereld!",
          "sportsTalent": "Horitoki",
          "services": "Categorieën",
          "sports": "Sport",
          "fitness_centers": "Fitnesscentra",
          "personal_trainers": "Persoonlijke Trainers",
          "federations": "Federaties",
          "clubs": "Clubs",
          "talents": "Talenten",
          // "new_in": "Nieuw Binnen",
          "view_all": "Alles Bekijken",
          "recently_joined": "Recent Lid Geworden",
          "profile": "Profiel",
          "blog": "Blog",
          "shop": "Winkel",
          "wishlist": "Verlanglijst",
          "notifications": "Meldingen",
          "my_orders": "Mijn Bestellingen",
          "faqs": "FAQs",
          "feedback": "Feedback",
          "privacy": "Privacybeleid",
          "settings": "Instellingen",
          "logout": "Uitloggen",
          "edit_profile": "Profiel Bewerken",
          "account_info": "Accountinformatie",
          "my_addresses": "Mijn Adressen",
          "change_password": "Wachtwoord Wijzigen",
          "change_my_password": "Mijn Wachtwoord Wijzigen",
          "login": "Inloggen",
          "remember_me": "Onthoud mij",
          "forget_password": "Wachtwoord Vergeten",
          "register": "Registreren",
          "sign_up": "Aanmelden",
          "username": "Gebruikersnaam",
          "email": "E-mail",
          "mobile": "Mobiel",
          "password": "Wachtwoord",
          "confirm_password": "Bevestig Wachtwoord",
          "age": "Leeftijd",
          "location": "Locatie",
          "gender": "Geslacht",
          "male": "Man",
          "female": "Vrouw",
          "reset_password":
              "Voer hieronder uw geregistreerde e-mailadres in\nom instructies voor het opnieuw instellen van het wachtwoord te ontvangen",
          "send": "Verzenden",
          "new_address": "Nieuw Adres Toevoegen",
          "old_password": "Oud Wachtwoord",
          "new_password": "Nieuw Wachtwoord",
          "change": "Veranderen",
          "comments": "Reacties",
          "add_comment": "Reactie toevoegen",
          "more_products": "Scroll omlaag om meer producten te bekijken",
          "related_products": "Gerelateerde Producten",
          "reviews": "Beoordelingen",
          "add_to_cart": "Toevoegen aan winkelwagen",
          "based_on": "Gebaseerd op",
          "just_now": "Vandaag",
          "days_ago": "dagen geleden",
          "write_review": "Schrijf een Beoordeling",
          "rate": "Beoordelen",
          "your_review": "Schrijf uw beoordeling",
          "write_a_review": "Schrijf een beoordeling",
          "review_text": "Wil je iets schrijven over dit product?",
          "remaining_characters": "tekens over",
          "submit_review": "Beoordeling indienen",
          "required_field": "Verplicht veld",
          "keyword_search": "Zoeken met trefwoorden",
          "about_sport_talent": "Over Sport Talent",
          "support": "Ondersteuning",
          "rate_experience": "Beoordeel uw ervaring",
          "additional_comment": "Aanvullende opmerkingen",
          "policy_policy": "Privacybeleid",
          "language": "Taal",
          "about_us": "Over ons",
          "rate_us": "Beoordeel ons",
          "my_cart": "Mijn Winkelwagen",
          "order": "Bestelling",
          "address1": "Adres",
          "address": "Adres",
          "address2": "Adres 2",
          "review_&_pay": "Beoordelen & Betalen",
          "place_order": "Bestelling Plaatsen",
          "subtotal": "Subtotaal",
          "shipping": "Verzending",
          "discount": "Korting",
          "total": "TOTAAL",
          "deliver_note": "Let op: de levering duurt 3-7 dagen",
          "confirm_order": "Bevestig Bestelling",
          "continue": "Doorgaan",
          "credit_card": "Creditcard",
          "card_no": "Kaartnummer",
          "expiry_date": "Vervaldatum (mm/jj)",
          "cvv": "CVV",
          "benifits": "Voordelen",
          "add_coupan": "Couponcode toevoegen",
          "buy_now": "Nu Kopen",
          "my_bookings": "Mijn Boekingen",
          "bookigs_not_found": "Geen boekingen gevonden op geselecteerde datum",
          "offers": "Aanbiedingen",
          "starting_with": 'Beginnend bij',
          "working_hours": "Werkuren",
          "book_now": "Nu Boeken",
          "book_a_pitch": "Boek een veld",
          "pick_duration": "Kies de duur van de boeking",
          "booking_type": "Type boeking",
          "pick_date": "Kies Datum en Tijd",
          "monday": "Maandag",
          "tuesday": "Dinsdag",
          "wednesday": "Woensdag",
          "thursday": "Donderdag",
          "friday": "Vrijdag",
          "saturday": "Zaterdag",
          "sunday": "Zondag",
          "total_price": "Totale Prijs",
          "proceed": "Doorgaan",
          "confirm_booking": "Bevestig Boeking",
          "booking": "Boekingsgegevens",
          "facilites": "Faciliteiten",
          "book_field": "Boek Veld",
          "whats_new": "Scroll omlaag om te zien wat nieuw is",
          "search": "Zoeken",
          "search_text": "Waar ben je naar op zoek?",
          "filter": "Filter",
          "categories": "Categorie",
          "brands": "Merken",
          "sort": "Sorteren",
          "new_arrival": "Nieuwe Aankomst",
          "low_to_high": "Laag naar Hoog",
          "high_to_low": "Hoog naar Laag",
          "top_rated": "Top Beoordeeld",
          "apply": "Toepassen",
          "add_your_talent": "Voeg uw Talent toe",
          "search_talent": "Zoek Talent ...",
          "view": "Bekijk",
          "talent": "Talent",
          "likes": "Likes",
          "watch_video": "Klik om de videosectie te bekijken",
          "contact_talent": "Neem contact op met dit talent",
          "form_fill": "Vul het onderstaande formulier in",
          "company_name": "Bedrijfsnaam/Persoonsnaam",
          "contact_no": "Contactnummer",
          "reason_for_contact": "Reden voor contact met dit talent",
          "live_chat": "Live Chat",
          "type_something": "Typ iets",
          "enter_coupan": "Voer de couponcode in",
          "coupan_invalid": "Ongeldige Couponcode!",
          "retry": "Opnieuw proberen",
          "discount_granted": "Korting Toegekend!",
          "code_expired": "Couponcode Verlopen!",
          "order_successful": "Bestelling Succesvol",
          "was_received": "is ontvangen",
          "check_email":
              "Controleer uw e-mail voor orderbevestiging en bezorgtermijnen",
          "continue_shopping": "Doorgaan met winkelen",
          "pending": "IN AFWACHTING",
          "canceled": "GEANNULEERD",
          "delivered": "GELEVERD",
          "shipped": "VERZONDEN",
          "service_charge": "Servicekosten",
          "birthday": "Verjaardag",
          "country_code": "Landcode",
          "phone": "Telefoon",
          "country": "Land",
          "city": "Stad",
          "postal_code": "Postcode",
          "save": "Opslaan",
          "fill_form": "Vul het onderstaande formulier in",
          "full_name": "Volledige naam",
          "parent_contact": "Contactnummer ouder",
          "describe": "Beschrijf dit talent",
          "scroll_down": "Scroll omlaag om te bekijken",
          "are_you_sure": "Weet u het zeker!",
          "want_to_exit": "Wilt u deze app afsluiten?",
          "change_lang_msg": "Wilt u de taal wijzigen?",
          "yes": "Ja",
          "no": "Nee",
          "alert": "Waarschuwing!",
          "ok": "Oké",
          "network_error": "Netwerkfout",
          "connect_network": "Verbind met een netwerk, alstublieft",
          "requestFailed": "Verzoek mislukt",
          "email_required": "E-mail is vereist",
          "password_required": "Wachtwoord is vereist",
          "password_too_short": "Het wachtwoord is te kort",
          "username_required": "Gebruikersnaam is vereist",
          "phone_required": "Telefoonnummer is vereist",
          "password_should_match":
              "Zorg ervoor dat uw wachtwoorden overeenkomen",
          "age_required": "Leeftijd is vereist",
          "location_required": "Locatie is vereist",
          "invalid_email": "Ongeldige e-mail",
          "password_invalid": "Ongeldig wachtwoord",
          "not_given": "Niet opgegeven",
          "name": "Naam",
          "sure_to_delete": "Weet u zeker dat u dit adres wilt verwijderen?",
          "check_order_confirmation": "Controleer uw orderbevestiging",
          "email_for_delivery": "E-mail voor bezorgingstijdlijn",
          "sure_to_delete_product":
              "Weet u zeker dat u dit product wilt verwijderen",
          "add_review": "Voeg alstublieft uw recensie toe",
          "rate_talent": "Beoordeel Talent",
          "sure_to_cancel_booking":
              "Weet u zeker dat u deze boeking wilt annuleren?",
          "products": "Producten",
          "cart_empty": "Zorg ervoor dat u product en adres heeft toegevoegd",
          "home": "Thuis",
          "payment_success": "Betaling geslaagd",
          "your_feedback": "Uw feedback hier",
          "sure": "Weet u het zeker?",
          "sure_add_feedback": "Wilt u deze feedback toevoegen?",
          "400": "400",
          "remaining_chars": " tekens over",
          "maximum_chars_reached": "Maximum aantal tekens bereikt",
          "review": "recensies",
          "day_ago": "dag geleden",
          "off": "UIT",
          "years": "jaren",
          "fill_below_form": "Vul het onderstaande formulier in",
          "full_name_required": "Volledige naam is vereist",
          "parent_contact_required": "Contactgegevens ouder zijn vereist",
          "describe_talent": "Beschrijf dit talent",
          "preferred_photo": "(1080 x 1080 px voorkeur)",
          "preferred_video": "(1280 x 1720 px voorkeur)",
          "found": "gevonden",
          "services_not_found": "Geen service gevonden",
          "total_capital": "TOTAAL",
          "view_talent": "Bekijk Talenten",
          "add_new_address": "Voeg nieuw adres toe",
          // "submit": "Indienen",
          "reschedule": "Opnieuw plannen",
          "cancel": "Annuleren",
          "reschedule_booking": "Opnieuw plannen van boeking",
          "change_booking_date_time": "Wijzig de boekingsdatum en -tijd",
          "rescheduled": "Opnieuw ingepland",
          "successfully_rescheduled": "Boeking succesvol opnieuw ingepland",
          "error_while_rescheduling":
              "Er is een fout opgetreden bij het opnieuw plannen van de boeking",
          "error_while_canceling":
              "Er is een fout opgetreden bij het annuleren van de boeking",
          "edit_address": "Adres bewerken",
          "success": "Succes",
          "address_deleted_successfully": "Adres succesvol verwijderd!",
          "quit_payment": "Wilt u betalingen stoppen",
          "no_order_created": "Nog geen bestelling gemaakt",
          "empty_wishlist": "Verlanglijst is leeg",
          "no_support_faqs": "Geen FAQ's gevonden over ondersteuning",
          "no_talent_faqs": "Geen FAQ's gevonden over talent",
          "thanks": "Bedankt",
          "feedback_recorded": "Uw feedback is opgenomen",
          "rating_recorded": "Uw beoordeling is opgenomen",
          "no_blogs": "Blogs zijn nog niet geüpload",
          "address_empty":
              "Zorg ervoor dat u een adres heeft toegevoegd en geselecteerd",
          "blogs_not_found": "Blogs niet gevonden",
          "service_not_found": "Service niet gevonden",
          "offers_not_found": "Aanbiedingen niet gevonden",
          "out_of_stock": "Uit voorraad",
          "added_success": "Succesvol toegevoegd",
          "thanks_for_adding_talent":
              "Bedankt voor het toevoegen van uw talent. Wacht geduldig op goedkeuring door de beheerder",
          "make_sure":
              "Zorg ervoor dat u afbeeldingen en video heeft toegevoegd",
          "new_products": "Scroll omlaag om te zien wat nieuw is",
          "empty_cart": "Lege winkelwagen",
          "add_rating":
              "Selecteer alstublieft uw beoordeling en voeg een opmerking toe",
          "validate_email": "Voer een geldig e-mailadres in",
          "okk": "Oké",
          "cancell": "Annuleren",
          "already_booked":
              "Dit veld is al geboekt op het geselecteerde tijdstip",
          "scroll_to_view": "Scroll omlaag om te bekijken",
          "bookings_not_created": "Nog geen boekingen gemaakt",
          "searched_prod_not_found": "Producten niet gevonden",
          "sure_to_delete_review":
              "Weet u zeker dat u deze recensie wilt verwijderen",
          "update_review": "Recensie bijwerken",
          "press_book_now":
              "Druk op de knop Nu boeken om deze service te boeken",
          "press_buy_now": "Druk op de knop Nu kopen om dit product te kopen",
          "service_booking_success": "Service succesvol geboekt",
          "added_data":
              "Selecteer alstublieft het type talent, geslacht en leeftijd",
          "recently_not_found": "Recente aanmeldingen niet gevonden",
          "please_signup": "Log alstublieft in",
          "signup": "Aanmelden",
          "oops": "Oeps!",
          "signup_required":
              "Het lijkt erop dat u niet bent ing elogd, u moet eerst inloggen...",
          "en": "Engels",
          "ar": "Arabisch",
          "terms_and_conditions":
              "Ik heb de algemene voorwaarden gelezen en ga ermee akkoord",
          "accept_terms": "Accepteer alstublieft de algemene voorwaarden",
          "code": "Code",
          "country_code_required": "Landcode vereist",
          "offer_percentage": "Aanbiedingspercentage: "
        }
      };
}
