import 'package:get/get.dart';

class LocalizationClass extends Translations {
  static getLocalizedKey(String key) {
    String currentLanguageCode = Get.locale!.languageCode;
    print('Localized key is: ${key}_$currentLanguageCode');
    return '${key}_$currentLanguageCode';
  }
  // LocalizationClass(){
  //   loadLanguages();
  // }

  // loadLanguages(){
//
  // }
  @override
  Map<String, Map<String, String>> get keys {
    // final _localizationString = {};
    // List<String> supportedLanguages = ['en', 'ar'];
    // for(final lang in supportedLanguages){
    // }
    // final jsonString = rootBundle.load('assets/transalations/en.json');
    // return {
    //   "en": {}
    // };
    const Map<String, String> lang_en = {
      "hello": "Hello world!",
      "sportsTalent": "Horitoki",
      "services": "Categories",
      "sports": "Sports",
      "fitness_centers": "Fitness\nCenters",
      "personal_trainers": "Personal\nTrainers",
      "federations": "Federations",
      "clubs": "Clubs",
      'talents': "Talents",
      "new_in": "New In",
      "view_all": "View All",
      "recently_joined": "Recently Joined",
      "profile": "Profile",
      "blog": "Blog",
      "shop": "Shop",
      "wishlist": "Wishlist",
      "notifications": "Notifications",
      "my_orders": "My Orders",
      "faqs": "FAQs",
      "feedback": "Feedback",
      "privacy": "Privacy Policy",
      "settings": "Settings",
      "logout": "Logout",
      "edit_profile": "Edit Profile",
      "account_info": "Account Info",
      "my_addresses": "My Addresses",
      "change_password": "Change Password",
      "change_my_password": "Change My Password",
      "login": "Login",
      "remember_me": "Remember Me",
      "forget_password": "Forget Password",
      "register": "Register",
      "sign_up": "Sign Up",
      "username": "Username",
      "email": "Email",
      "mobile": "Mobile",
      "password": "Password",
      "confirm_password": "Confirm Password",
      "age": "Age",
      "location": "Location",
      "gender": "Gender",
      "male": "Male",
      "female": "Female",
      "reset_password":
          "Enter your registered email below to\nreceive password reset instructions",
      "send": "Send",
      "new_address": "Add New Address",
      "old_password": "Old Password",
      "new_password": "New Password",
      "change": "Change",
      "comments": "Comments",
      "add_comment": "Add a comments",
      "more_products": "Scroll down to view more products",
      "related_products": "Related Products",
      "reviews": "Reviews",
      "add_to_cart": "Add to Cart",
      "based_on": "Based on",
      "just_now": "Today",
      "days_ago": "days ago",
      "write_review": "Write a Review",
      "rate": "Rate",
      "your_review": "Write your review",
      "write_a_review": "Write a review",
      "review_text": "Would you like to write anything about this product?",
      "remaining_characters": "characters remaining",
      "submit_review": "Submit Review",
      "required_field": "Required Field",
      "keyword_search": "Search using keywords",
      "about_sport_talent": "About Sport Talent",
      "support": "Support",
      "rate_experience": "Please rate your experience",
      "additional_comment": "Additional comments",
      "policy_policy": "Privacy Policy",
      "language": "Language",
      "about_us": "About us",
      "rate_us": "Rate us",
      "my_cart": "My Cart",
      "order": "Order",
      "address1": "Address",
      "address": "Address",
      "address2": "Address 2",
      "review_&_pay": "Review & Pay",
      "place_order": "Place Order",
      "subtotal": "Subtotal",
      "shipping": "Shipping",
      "discount": "Discount",
      "total": "TOTAL",
      "deliver_note": "Please note that the delivery will take 3-7 days",
      "confirm_order": "Confirm Order",
      "continue": "Continue",
      "credit_card": "Credit Card",
      "card_no": "Card Number",
      "expiry_date": "Expiry Date (mm/yy)",
      "cvv": "CVV",
      "benifits": "Benifits",
      "add_coupan": "Add Coupon Code",
      "buy_now": "Buy Now",
      "my_bookings": "My Bookings",
      "bookigs_not_found": "Bookings not found on selected date",
      "offers": "Offers",
      "starting_with": 'Starting with',
      "working_hours": "Working Hours",
      "book_now": "Book Now",
      "book_a_pitch": "Book a pitch",
      "pick_duration": "Pick duration of booking",
      "booking_type": "Booking type",
      "pick_date": "Pick Date and Time",
      "monday": "Monday",
      "tuesday": "Tuesday",
      "wednesday": "Wednesday",
      "thursday": "Thursday",
      "friday": "Friday",
      "saturday": "Saturday",
      "sunday": "Sunday",
      "total_price": "Total Price",
      "proceed": "Proceed",
      "confirm_booking": "Confirm Booking",
      "booking": "Booking Details",
      "facilites": "Facilities",
      "book_field": "Book Field",
      "whats_new": "Scroll down to see what's new",
      "search": "Search",
      "search_text": "What are you looking for?",
      "filter": "Filter",
      "categories": "Category",
      "brands": "Brands",
      "sort": "Sort",
      "new_arrival": "New Arriavals",
      "low_to_high": "Low to High",
      "high_to_low": "High to Low",
      "top_rated": "Top Rated",
      "apply": "Apply",
      "add_your_talent": "Add Your Talent",
      "search_talent": "Search Talent ...",
      "view": "View",
      "talent": "Talent",
      "likes": "Likes",
      "watch_video": "Click to watch the video section",
      "contact_talent": "Contact this talent",
      "form_fill": "Kindly fill the form below",
      "company_name": "Company/Person Name",
      "contact_no": "Contact Number",
      "reason_for_contact": "Reason for contacting this talent",
      "live_chat": "Live Chat",
      "type_something": "Type something",
      "enter_coupan": "Enter coupon code",
      "coupan_invalid": "Coupon Code Invalid!",
      "retry": "Retry",
      "discount_granted": "Discount Granted!",
      "code_expired": "Coupon Code Expired!",
      "order_successful": "Order Successful",
      "was_received": "was received",
      "check_email":
          "Please check your order confirmation email for delivery timelines",
      "continue_shopping": "Continue Shopping",
      "pending": "PENDING",
      "canceled": "CANCELED",
      "delivered": "DELIVERED",
      "shipped": "SHIPPED",
      "service_charge": "Service Charge",
      "birthday": "Birthday",
      "country_code": "Country Code",
      "phone": "Phone",
      "country": "Country",
      "city": "City",
      "postal_code": "Postal code",
      "save": "Save",
      "fill_form": "Please fill the form below",
      "full_name": "Full name",
      "parent_contact": "Parent contact number",
      "describe": "Describe this talent",
      "scroll_down": "Scroll down to view",
      "are_you_sure": "Are you sure!",
      "want_to_exit": "Do you want to exit this app?",
      "change_lang_msg": "Dou want to change language?",
      "yes": "Yes",
      "no": "No",
      "alert": "Alert!",
      "ok": "Ok",
      "network_error": "Network error",
      "connect_network": 'Please connect to a network',
      "requestFailed": "Resuest failed",
      "email_required": "Email is required",
      "password_required": "Password is required",
      "password_too_short": "The password is too short",
      "username_required": "Username is required",
      "phone_required": "Phone no is required",
      "password_should_match": "Please make sure your passwords match",
      "age_required": "Age is required",
      "location_required": "Location is required",
      "invalid_email": "Invalid Email",
      "password_invalid": "Invalid Password",
      "not_given": "Not Given",
      "name": "Name",
      "sure_to_delete": "Are you sure to delete this address?",
      "check_order_confirmation": "Please check your order confirmation ",
      "email_for_delivery": "Email for delivery timeline",
      "sure_to_delete_product": "Are you sure to delete this product",
      "add_review": "Please add your reveiw",
      "rate_talent": "Rate Talent",
      "sure_to_cancel_booking": "Are you sure to cancel this booking?",
      'products': "Products",
      "cart_empty": "Please ensure you have added product and address",
      "home": 'Home',
      "payment_success": "Payment Successful",
      "your_feedback": "Your feedback goes here",
      "sure": 'Are you sure?',
      "sure_add_feedback": "Do you want add this feedback?",
      "400": "400",
      "remaining_chars": " characters remaining",
      "maximum_chars_reached": "Maximum characters reached",
      "review": "reviews",
      "day_ago": "day ago",
      "off": "OFF",
      "years": "years",
      "fill_below_form": "Please fill the form below",
      "full_name_required": "Full name is required",
      "parent_contact_required": "Parent contact is required",
      "describe_talent": "Describe this talent",
      "preferred_photo": "(1080 x 1080 px preferred)",
      "preferred_video": "(1280 x 1720 px preferred)",
      "found": "found",
      "services_not_found": "No Service found",
      "total_capital": "TOTAL",
      'view_talent': "View Talents",
      "add_new_address": "Add New Address",
      "submit": "Submit",
      "reschedule": "Reschedule",
      "cancel": "Cancel",
      "reschedule_booking": "Reschedule Booking",
      "change_booking_date_time": "Change booking date and time",
      "rescheduled": "Rescheduled",
      "successfully_rescheduled": "Booking successfully rescheduled",
      "error_while_rescheduling": "An error occured while rescheduling booking",
      "error_while_canceling": "An error occured while canceling booking",
      "edit_address": "Edit Address",
      "success": "Success",
      "address_deleted_successfully": "Address deleted successfully!",
      "quit_payment": "Do you want to quit payments",
      "no_order_created": "No order created yet",
      "empty_wishlist": "Wishlist is empty",
      "no_support_faqs": "No FAQ's found for about support",
      "no_talent_faqs": "No FAQ's found for about talent",
      "thanks": "Thanks",
      "feedback_recorded": "Your feedback is recorded",
      "rating_recorded": "You rating is recorded",
      "no_blogs": "Blogs are not uploaded yet",
      "address_empty": "Please make sure you have added and selected address",
      "blogs_not_found": "Blogs not found",
      "service_not_found": "Service not found",
      "offers_not_found": "Offers not found",
      "out_of_stock": "Out of Stock",
      "added_success": "Successfully Added",
      "thanks_for_adding_talent":
          "Thanks for adding your talent. Please be patient till admin approval",
      "make_sure": "Please make sure you have added images and video",
      "new_products": "Scroll down to see what's new",
      "empty_cart": "Empty Cart",
      "add_rating": "Please select your rating and add comment",
      "validate_email": "Enter a valid email address",
      "okk": "Ok",
      "cancell": "Cancel",
      "already_booked": "This field is already booked at the selected time",
      "scroll_to_view": "Scroll down to view",
      "bookings_not_created": "Bookings not created yet",
      "searched_prod_not_found": "Products not found",
      "sure_to_delete_review": "Are you sure to delete this review",
      "update_review": "Update Review",
      "press_book_now": "Press Book Now button to book this service",
      "press_buy_now": "Press Buy Now button to buy this product",
      "service_booking_success": "Service Booked Successfully",
      "added_data": "Please select talent type, gender and age",
      "recently_not_found": "Recently joinies not found",
      "please_signup": "Please Login",
      "signup": "Sign up",
      "oops": "Oops!",
      "signup_required":
          "It look like you are not Logged In, You need to login first...",
      'en': "English",
      'ar': "Arabic",
      "terms_and_conditions": "I have read and accept terms and conditions",
      "accept_terms": "Please accept the terms and conditions",
      "code": "Code",
      "country_code_required": "country code required",
      "offer_percentage": "Offer Percentage: ",
    };

    const Map<String, String> lang_ar = {
      "hello": "مرحبا بالعالم!",
      "sportsTalent": "المواهب الرياضية",
      "services": "الخدمات",
      "sports": "الرياضات",
      "fitness_centers": "مراكز اللياقة\nالبدنية",
      "personal_trainers": "المدربين\nالشخصيين",
      "federations": "الاتحادات",
      "clubs": "النوادي",
      "talents": "المواهب",
      "new_in": "الجديد",
      "view_all": "مشاهدة المزيد",
      "recently_joined": "انضم مؤخرا",
      "profile": "الملف الشخصي",
      "blog": "المدونة",
      "shop": "المتجر",
      "wishlisht": "قائمة الرغبات",
      "notifications": "الإشعارات",
      "my_orders": "طلباتي",
      "faqs": "الأسئلة الشائعة",
      "feedback": "التقييمات",
      "privacy": "الخصوصية",
      "settings": "الإعدادات",
      "logout": "تسجيل الخروج",
      "edit_profile": "تعديل الملف الشخصي",
      "account_info": "معلومات الحساب",
      "my_addresses": "عنواني",
      "change_password": "تغيير كلمة المرور الخاصة بي",
      'change_my_password': "تغيير كلمة المرور الخاصة بي",
      "login": "تسجيل الدخول",
      "remember_me": "تذكرني",
      "forget_password": "هل نسيت كلمة المرور",
      "register": "التسجيل",
      "sign_up": "التسجيل",
      "username": "اسم المستخدم",
      "email": "البريد الإلكتروني",
      "mobile": "رقم الهاتف",
      "password": "كلمة المرور",
      "confirm_password": "تأكيد كلمة المرور",
      "age": "العمر",
      "location": "الموقع",
      "gender": "الجنس",
      "male": "ذكر",
      "female": "أنثى",
      "reset_password":
          "أدخل بريدك الإلكتروني المسجل أدناه\nللحصول على تعليمات إعادة تعيين كلمة المرور",
      "send": "إرسال",
      "new_address": "إضافة عنوان جديد",
      "old_password": "كلمة المرور القديمة",
      "new_password": "كلمة المرور الجديدة",
      "change": "تغيير",
      "comments": "التعليقات",
      "add_comment": "إضافة تعليق",
      "more_products": "المنتجات الرياضية",
      "related_products": "منتجات ذات صله",
      "reviews": "مراجعة",
      "add_to_cart": "أضف إلى السلة",
      "based_on": "مبني على",
      "just_now": "اليوم",
      "days_ago": "أيام مضت",
      "write_review": "أكتب تعليق",
      "rate": "تقييم",
      "your_review": "أكتب تعليقك",
      "write_a_review": "أكتب تعليقك",
      "review_text": "هل تود في كتابة أي شيء عن هذا المنتج؟",
      "remaining_characters": "حرف متبقي",
      "submit_review": "إرسال المراجعة",
      "required_field": "حقل مطلوب",
      "keyword_search": "البحث باستخدام الكلمات المفتاحية",
      "about_sport_talent": "نبذة عن المواهب الرياضية",
      "support": "الدعم",
      "rate_experience": "من فضلك قيم تجربتك",
      "additional_comment": "تعليقات إضافية",
      "policy_policy": "سياسة الخصوصية",
      "language": "اللغة",
      "about_us": "من نحن",
      "rate_us": "قيمنا",
      "my_cart": "السلة",
      "order": "الطلب",
      "address1": "العنوان",
      "address": "1 العنوان",
      "address2": "2 العنوان",
      "review_&_pay": "المراجعة والدفع",
      "place_order": "إتمام الطلب",
      "subtotal": "المجموع",
      "shipping": "الشحن",
      "discount": "خصم",
      "total": "المجموع",
      "deliver_note": "يرجى ملاحظة أن التسليم سيستغرق 3-7 أيام",
      "confirm_order": "تأكيد الطلب",
      "continue": "متابعة",
      "credit_card": "بطاقة الائتمان",
      "card_no": "رقم البطاقة",
      "expiry_date": "تاريخ انتهاء الصلاحية (شهر / سنة)",
      "cvv": "CVV",
      "benifits": "بنفت",
      "add_coupan": "أضف رمز القسيمة",
      "buy_now": "اشتري الآن",
      "my_bookings": "حجوزاتي",
      "bookigs_not_found": "الحجوزات غير موجودة في التاريخ المحدد",
      "offers": "العروض",
      "starting_with": "بدءا من",
      "working_hours": "ساعات العمل",
      "book_now": "احجز الآن",
      "book_a_pitch": "احجز ملعب",
      "pick_duration": "اختر مدة الحجز",
      "booking_type": "نوع الحجز",
      "pick_date": "اختر التاريخ والوقت",
      "monday": "الإثنين",
      "tuesday": "الثلاثاء",
      "wednesday": "الأربعاء",
      "thursday": "الخميس",
      "friday": "الجمعة",
      "saturday": "السبت",
      "sunday": "الأحد",
      "total_price": "السعر الكلي",
      "proceed": "متابعة",
      "confirm_booking": "تأكيد الحجز",
      "booking": "الحجز",
      "facilites": "الخدمات",
      "book_field": "احجز ملعب",
      "whats_new": "مشاهدة الجديد",
      "search": "بحث",
      "search_text": "ما الذي تبحث عنه؟",
      "filter": "تصفية",
      "categories": "التصنيفات",
      "brands": "العلامات التجارية",
      "sort": "فرز",
      "new_arrival": "وصل حديثًا",
      "low_to_high": "من الأقل إلى الأعلى",
      "high_to_low": "من الأعلى إلى الأقل",
      "top_rated": "أعلى التقييمات",
      "apply": "تطبيق",
      "add_your_talent": "أضف موهبتك",
      "search_talent": "البحث عن موهبة ...",
      "view": "معاينة",
      "talent": "الموهبة",
      "likes": "الإعجابات",
      "watch_video": "اضغط لمشاهدة مقطع الفيديو",
      "contact_talent": "تواصل مع هذه الموهبة",
      "form_fill": "الرجاء تعبئة النموذج أدناه",
      "company_name": "اسم الشركة / الشخص",
      "contact_no": "رقم الاتصال",
      "reason_for_contact": "سبب التواصل مع هذه الموهبة",
      "live_chat": "تواصل معنا",
      "type_something": "اكتب شيئًا",
      "enter_coupan": "أدخل رمز القسيمة",
      "coupan_invalid": "رمز القسيمة غير صالح!",
      "retry": "أعد المحاولة",
      "discount_granted": "تم منح الخصم!",
      "code_expired": "انتهت صلاحية رمز القسيمة!",
      "order_successful": "تم الطلب بنجاح",
      "was_received": "تم الاستلام",
      "check_email":
          "يرجى التحقق من رسالة تأكيد الطلب في بريدك الإلكتروني لمعرفة وقت استلام الطلب",
      "continue_shopping": "مواصلة التسوق",
      "pending": "قيد الانتظار",
      "canceled": "ملغي",
      "delivered": "تم التوصيل",
      "shipped": "تم الشحن",
      "service_charge": "تكلفة الخدمة",
      "birthday": "تاريخ الميلاد",
      "country_code": "الرقم الدولي",
      "phone": "رقم الهاتف",
      "country": "البلد",
      "city": "المدينة",
      "postal_code": "الرمز البريدي",
      "save": "حفظ",
      "fill_form": "يرجى ملء النموذج أدناه",
      "full_name": "الاسم الكامل",
      "parent_contact": "رقم التواصل مع ولي الأمر",
      "describe": "صف هذه الموهبة",
      "upload_photo": "تحميل صورة",
      "click_to_upload": "اضغط هنا للتحميل",
      "upload_video": "تحميل الفيديو",
      "scroll_down": "انزل لأسفل",
      "are_you_sure": "هل أنت متأكد!",
      "want_to_exit": "هل تريد الخروج من هذا التطبيق؟",
      "change_lang_msg": "هل تريد تغيير اللغة؟",
      "yes": "نعم",
      "no": "كلا",
      "alert": "تنبيه!",
      "ok": "حسنا",
      "network_error": "خطأ في الشبكة",
      "connect_network": "الرجاء الاتصال بالشبكة",
      "requestFailed": "فشل طلب الشبكة",
      "email_required": "البريد الإلكتروني مطلوب",
      "password_required": "كلمة المرور مطلوبة",
      "password_too_short": "كلمة المرور قصيرة جدا",
      "username_required": "اسم المستخدم مطلوب",
      "phone_required": "رقم الهاتف مطلوب",
      "password_should_match": "يرجى التأكد من تطابق كلمتي المرور الخاصة بك",
      "age_required": "العمر مطلوب",
      "location_required": "الموقع مطلوب",
      "invalid_email": "البريد الإلكتروني غير صحيح",
      "password_invalid": "كلمة المرور غير صحيحة",
      "not_given": "غير معطى",
      "name": "الاسم",
      "sure_to_delete": "هل أنت متأكد من حذف هذا العنوان؟",
      "check_order_confirmation": "يرجى التحقق من تأكيد الطلب الخاص بك ",
      "email_for_delivery": "البريد الإلكتروني للجدول الزمني للتسليم",
      "sure_to_delete_product": "هل أنت متأكد من حذف هذا المنتج",
      "add_review": "الرجاء إضافة رأيك",
      "rate_talent": "تقييم الموهبة",
      "sure_to_cancel_booking": "هل أنت متأكد من إلغاء هذا الحجز؟",
      "products": "المنتجات",
      "cart_empty": "يرجى التأكد من إضافة المنتج والعنوان",
      "home": "الرئيسية",
      "payment_success": "تم الدفع بنجاح",
      "your_feedback": "ملاحظاتك هنا",
      "sure": "هل أنت متأكد؟",
      "sure_add_feedback": "هل تريد إضافة هذه التقييمات؟",
      "400": "400",
      "view_talent": "مشاهدة ملف",
      "remaining_chars": "الأحرف المتبقية",
      "maximum_chars_reached": "تم الوصول إلى الحد الأقصى من الأحرف",
      "review": "إعادة النظر",
      "off": "إيقاف",
      "day_ago": "منذ يوم",
      "fill_below_form": "يرجى ملء النموذج أدناه",
      "full_name_required": "الإسم الكامل ضروري",
      "parent_contact_required": "مطلوب الاتصال بالوالدين",
      "describe_talent": "صف هذه الموهبة",
      "preferred_photo": "(يفضل 1080 × 1080 بكسل)",
      "preferred_video": "(يُفضل 1280 × 1720 بكسل)",
      "found": "وجدت",
      "services_not_found": "الخدمات غير موجودة",
      "total_capital": "المجموع",
      "add_new_address": "أضف عنوان جديد",
      "submit": "إرسال",
      "reschedule": "إعادة الجدولة",
      "cancel": "إلغاء",
      "reschedule_booking": "إعادة جدولة الحجز",
      "change_booking_date_time": "تغيير تاريخ الحجز ووقته",
      "rescheduled": "تمت إعادة جدولته",
      "successfully_rescheduled": "تمت إعادة جدولة الحجز بنجاح",
      "error_while_resheduling": "حدث خطأ أثناء إعادة جدولة الحجز",
      "error_while_canceling": "حدث خطأ أثناء إلغاء الحجز",
      "edit_address": "تعديل العنوان",
      "success": "النجاح",
      "address_deleted_successfully": "تم حذف العنوان بنجاح!",
      "quit_payment": "هل تريد إنهاء المدفوعات",
      "no_order_created": "لم يتم إنشاء أي طلب حتى الآن",
      "wishlist": "قائمة الرغبات",
      "empty_wishlist": "قائمة الرغبات فارغة",
      "no_talent_faqs": "لا توجد أسئلة شائعة حول الموهبة",
      "no_support_faqs": "لم يتم العثور على أسئلة وأجوبة حول الدعم",
      "thanks": "شكرا",
      "feedback_recorded": "يتم تسجيل ملاحظاتك",
      "rating_recorded": "تم تسجيل تقييمك",
      "no_blogs": "لم يتم تحديث المدونات بعد",
      "address_empty": "يرجى التأكد من أنك قمت بإضافة واختيار العنوان",
      "blogs_not_found": "المدونات غير موجودة",
      "service_not_found": "الخدمة غير موجودة",
      "offers_not_found": "العروض غير موجودة",
      "out_of_stock": "إنتهى من المخزن",
      "added_success": "أضيف بنجاح",
      "thanks_for_adding_talent":
          "شكرا لإضافة موهبتك. يرجى التحلي بالصبر حتى موافقة المسؤول",
      "make_sure": "يرجى التأكد من إضافة الصور والفيديو",
      "new_products": "قم بالتمرير لأسفل لمعرفة الجديد",
      "empty_cart": "عربة فارغة",
      "add_rating": "الرجاء تحديد تقييمك وإضافة تعليق",
      "validate_email": "أدخل عنوان بريد إلكتروني صالح",
      "okk": "نعم",
      "cancell": "كلا",
      "already_booked": "هذا الحقل محجوز بالفعل في الوقت المحدد",
      "scroll_to_view": "انتقل لأسفل لعرض",
      "bookings_not_created": "الحجوزات لم يتم إنشاؤها بعد",
      "searched_prod_not_found":
          "لم يتم العثور على المنتجات التي تم البحث عنها",
      "sure_to_delete_review": "هل أنت متأكد من حذف هذه المراجعة",
      "update_review": "تحديث المراجعة",
      "press_book_now": "اضغط على زر احجز الآن لحجز هذه الخدمة",
      "press_buy_now": "اضغط على زر الشراء الآن لشراء هذا المنتج",
      "service_booking_success": "تم حجز الخدمة بنجاح",
      "added_data": "يرجى تحديد نوع الموهبة والجنس والعمر",
      "recently_not_found": "مؤخرا لم يتم العثور على المنضمين",
      "please_signup": "يرجى الاشتراك",
      "signup": "اشتراك",
      "signup_required": "التسجيل مطلوب للوصول إليه. انقر أدناه للتسجيل",
      'en': "إنجليزي",
      'ar': "عربى",
      'terms_and_conditions': "لقد قرأت وقبلت الشروط والأحكام",
      "accept_terms": "الرجاء قبول الشروط والأحكام",
      "code": "الشفرة",
      "country_code_required": "كود الدولة مطلوب",
      "offer_percentage": " :نسبة العرض"
    };

    return {
      'en': lang_en,
      'ar': lang_ar,
    };
  }
}
