// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-N_pQ1wIEaomTdSAZ9XPmGK0NldxtxI',
    appId: '1:156442496426:web:c0038299b2a3464607afd3',
    messagingSenderId: '156442496426',
    projectId: 'home-decor-11796',
    authDomain: 'home-decor-11796.firebaseapp.com',
    storageBucket: 'home-decor-11796.appspot.com',
    measurementId: 'G-M7EN3BF6WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Vzhw_CglbFCxmBpMyrGtu9ml85yisTM',
    appId: '1:156442496426:android:4bdb17825341222f07afd3',
    messagingSenderId: '156442496426',
    projectId: 'home-decor-11796',
    storageBucket: 'home-decor-11796.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKtGsg_8JWpLnXxyFk009NER_HTTZRKyQ',
    appId: '1:156442496426:ios:c0e2412527b67dc307afd3',
    messagingSenderId: '156442496426',
    projectId: 'home-decor-11796',
    storageBucket: 'home-decor-11796.appspot.com',
    iosBundleId: 'com.example.f2BaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKtGsg_8JWpLnXxyFk009NER_HTTZRKyQ',
    appId: '1:156442496426:ios:a9c7ff9c920e52b007afd3',
    messagingSenderId: '156442496426',
    projectId: 'home-decor-11796',
    storageBucket: 'home-decor-11796.appspot.com',
    iosBundleId: 'com.example.f2BaseProject.RunnerTests',
  );
}
